# Configuration file for NextQR Application

# ================= GENERAL INFO =================
[app]
build = "27.11.2022"
name = "NextQR"
version = ".alpha-0.0.1"
auto_build = false

[screen]
size = "900x600"
resizable_width = false
resizable_height = false
appearance_mode = "dark"
color_theme = "blue"

[font]
size_S = 8
size_M = 10
title_size_M = 14
title_size_L = 18
roboto = "Roboto Medium"

[path]
icons = ""

[link]
github = "https://github.com/Mova801"

# ================= IMAGES =================
[image]
[image.logo]
path = "src/images/logo.ico"

[image.github]
size = 32
path = "src/images/github.png"

[image.bug]
size = 22
path = "src/images/bug.png"

# ================= LAYOUT =================
[layout]
[layout.button]
width = 80
height = 35
img_position = "left"

[layout.entry]
width = 300
height = 35

[layout.textbox]
width = 600
height = 200

[layout.image_frame]
width = 600
height = 150

[layout.left_frame]
scale_factor = 5
inner_padx = 20
sticky = "nsew"

[layout.right_frame]
scale_factor = 5
padding = 8
corner_radius = 15
inner_padx = 20
sticky = "nsew"